In [21]:
import pandas as pd
students=pd.read_csv('students.csv')
courses=pd.read_csv('courses.csv')
attendance=pd.read_csv('attendance.csv')
grades=pd.read_csv('grades.csv')

In [22]:
df=attendance.merge(students,on="StudentID")
df=df.merge(courses, on="CourseID")
df=df.merge(grades,on="StudentID")
print(df.columns)

Index(['AttendanceID', 'StudentID', 'CourseID_x', 'Date_x', 'AttendanceStatus',
       'FirstName', 'LastName', 'Gender', 'DateOfBirth', 'Major', 'GPA',
       'CourseName', 'Department', 'Credits', 'Instructor', 'GradeID',
       'CourseID_y', 'AssignmentType', 'Score', 'Date_y'],
      dtype='object')

In [23]:
print(df)

      AttendanceID  StudentID CourseID_x      Date_x AttendanceStatus  \
0                1       1086    COURSE6  2022-06-07           Absent
1                3       1320   COURSE29  2020-11-10          Present
2                4       1327   COURSE32  2024-01-15          Present
3                4       1327   COURSE32  2024-01-15          Present
4                4       1327   COURSE32  2024-01-15          Present
...            ...        ...        ...         ...              ...
1948           999       1121   COURSE43  2020-11-21           Absent
1949           999       1121   COURSE43  2020-11-21           Absent
1950           999       1121   COURSE43  2020-11-21           Absent
1951           999       1121   COURSE43  2020-11-21           Absent
1952          1000       1355    COURSE8  2024-07-29          Present

       FirstName LastName  Gender DateOfBirth             Major   GPA  \
0      Student86      Doe    Male  1993-11-21       Mathematics  3.80
1     Student320      Doe  Female  2004-01-07       Mathematics  3.87
2     Student327      Doe    Male  1998-12-27           Physics  3.67
3     Student327      Doe    Male  1998-12-27           Physics  3.67
4     Student327      Doe    Male  1998-12-27           Physics  3.67
...          ...      ...     ...         ...               ...   ...
1948  Student121      Doe    Male  1990-02-27           Biology  3.77
1949  Student121      Doe    Male  1990-02-27           Biology  3.77
1950  Student121      Doe    Male  1990-02-27           Biology  3.77
1951  Student121      Doe    Male  1990-02-27           Biology  3.77
1952  Student355      Doe  Female  2002-03-27  Computer Science  2.88

     CourseName        Department  Credits     Instructor  GradeID CourseID_y  \
0      Course 6  Computer Science        2   Instructor 6      605   COURSE41
1     Course 29       Mathematics        1  Instructor 29      580   COURSE10
2     Course 32  Computer Science        4  Instructor 32      295   COURSE21
3     Course 32  Computer Science        4  Instructor 32      811   COURSE50
4     Course 32  Computer Science        4  Instructor 32      950   COURSE39
...         ...               ...      ...            ...      ...        ...
1948  Course 43           Physics        3  Instructor 43       92   COURSE28
1949  Course 43           Physics        3  Instructor 43      691   COURSE13
1950  Course 43           Physics        3  Instructor 43      776   COURSE12
1951  Course 43           Physics        3  Instructor 43      939   COURSE41
1952   Course 8           Physics        3   Instructor 8      954   COURSE46

     AssignmentType  Score      Date_y
0        Assignment     64  2021-08-31
1           Midterm     78  2021-02-27
2        Final Exam     74  2022-09-05
3        Assignment     60  2022-09-19
4              Quiz     81  2024-09-11
...             ...    ...         ...
1948           Quiz     94  2023-04-03
1949     Final Exam     83  2021-09-26
1950           Quiz     80  2022-09-30
1951           Quiz     72  2023-10-10
1952        Midterm     65  2020-08-30

[1953 rows x 20 columns]

In [24]:
final_df=df[["StudentID","FirstName","Department","Score","Date_y","AttendanceStatus"]]
print(final_df.columns)

Index(['StudentID', 'FirstName', 'Department', 'Score', 'Date_y',
       'AttendanceStatus'],
      dtype='object')

In [25]:
final_df.head()

   StudentID   FirstName        Department  Score      Date_y AttendanceStatus
0       1086   Student86  Computer Science     64  2021-08-31           Absent
1       1320  Student320       Mathematics     78  2021-02-27          Present
2       1327  Student327  Computer Science     74  2022-09-05          Present
3       1327  Student327  Computer Science     60  2022-09-19          Present
4       1327  Student327  Computer Science     81  2024-09-11          Present

In [26]:
from faker import Faker
fake=Faker()
final_df["FirstName"]=[fake.first_name() for i in range(len(final_df))]
print(final_df.head())

   StudentID FirstName        Department  Score      Date_y AttendanceStatus
0       1086      Dale  Computer Science     64  2021-08-31           Absent
1       1320      John       Mathematics     78  2021-02-27          Present
2       1327     Scott  Computer Science     74  2022-09-05          Present
3       1327      Todd  Computer Science     60  2022-09-19          Present
4       1327     Bryce  Computer Science     81  2024-09-11          Present

C:\Users\dream\AppData\Local\Temp\ipykernel_16196\654365331.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["FirstName"]=[fake.first_name() for i in range(len(final_df))]

In [28]:
final_df.columns=["student_id","name","subject","score","date","attendance"]
print(final_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1953 entries, 0 to 1952
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  1953 non-null   int64
 1   name        1953 non-null   object
 2   subject     1953 non-null   object
 3   score       1953 non-null   int64
 4   date        1953 non-null   object
 5   attendance  1953 non-null   object
dtypes: int64(2), object(4)
memory usage: 91.7+ KB
None

In [29]:
print(final_df)

      student_id       name           subject  score        date attendance
0           1086       Dale  Computer Science     64  2021-08-31     Absent
1           1320       John       Mathematics     78  2021-02-27    Present
2           1327      Scott  Computer Science     74  2022-09-05    Present
3           1327       Todd  Computer Science     60  2022-09-19    Present
4           1327      Bryce  Computer Science     81  2024-09-11    Present
...          ...        ...               ...    ...         ...        ...
1948        1121      Jamie           Physics     94  2023-04-03     Absent
1949        1121  Katherine           Physics     83  2021-09-26     Absent
1950        1121    Michael           Physics     80  2022-09-30     Absent
1951        1121    Allison           Physics     72  2023-10-10     Absent
1952        1355     Thomas           Physics     65  2020-08-30    Present

[1953 rows x 6 columns]

In [30]:
final_df.columns=final_df.columns.str.strip()

In [31]:
#to add null values in subject column
import numpy as np
rows=np.random.choice(final_df.index ,size=98,replace=False)
final_df.loc[rows,"subject"]=np.nan

In [33]:
rows=np.random.choice(final_df.index ,size=195,replace=False)
final_df.loc[rows,"attendance"]=np.nan

In [34]:
rows=np.random.choice(final_df.index ,size=23,replace=False)
final_df.loc[rows,"name"]=np.nan

In [35]:
rows=np.random.choice(final_df.index ,size=255,replace=False)
final_df.loc[rows,"date"]=np.nan

In [36]:
rows=np.random.choice(final_df.index ,size=316,replace=False)
final_df.loc[rows,"score"]=np.nan

In [37]:
final_df.isnull().sum()

student_id      0
name           23
subject        98
score         316
date          255
attendance    374
dtype: int64

In [38]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1953 entries, 0 to 1952
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  1953 non-null   int64
 1   name        1930 non-null   object
 2   subject     1855 non-null   object
 3   score       1637 non-null   float64
 4   date        1698 non-null   object
 5   attendance  1579 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 91.7+ KB

In [39]:
#to check all scores less than 100
final_df[final_df["score"]>100]

Empty DataFrame
Columns: [student_id, name, subject, score, date, attendance]
Index: []

In [40]:
df_with_dupes=pd.concat([final_df,final_df.sample(50)])

In [41]:
df_with_dupes.duplicated().sum()

np.int64(50)

In [42]:
df_with_dupes.to_csv("raw_students.csv",index=False)